### ISSUE TITLE
Milestone 1: Feedback

### ISSUE THREAD

**Issue by angpeihao98** [ICT2201-p1-3/ICT2x01-Team-Project_p1-3#38]
Feedback of Milestone 1

**Comment by Meh1** [comment]
Milestone 1 feedback
Background literature is extra research into the topic
2 Overall Description and other sections should have a summary paragraph
Product functionality should be concise
Cannot assume what customer wants for user interface requirements, user interface requirements are ( what color scheme should be used, in hexadecimal, how big buttons should be for older users, multiple languages for user)
<<Extends>> instead of <Extends>, some use case can be alternative scenario, cut down cost
Extension points
Estimation of Effort in real world scenario done in first few meetings, determine if the project is realistic to be done within the allocated time.
Estimation of Effort 100 days is too long for this project, therefore need to reduce use case (alternative scenario)
