### ISSUE TITLE
Milestone 1 Retrospective: What we will commit to improve in the next milestone 1

### ISSUE THREAD

**Issue by angpeihao98** [ICT2201-p1-3/ICT2x01-Team-Project_p1-3#41]
Keep everyone on track by indicating our progress on slack more frequently.

**Comment by chsiang469** [comment]
Instead of slack, we chose to use a separate group chat to frequently update one another on the changes that we have made, and the tasks that we are planning to do. We also frequently checked in and gathered inputs from one another.


![Image](https://user-images.githubusercontent.com/25312335/198818154-7c059451-d8de-4252-af1a-414585020442.png)
